-- SQL script to insert the 50 most common countries plus "Globally"
-- Run this script to populate the Countries table

INSERT INTO Countries (name, code, createdAt, updatedAt) VALUES
('Globally', 'GL', NOW(), NOW()),
('United States', 'US', NOW(), NOW()),
('China', 'CN', NOW(), NOW()),
('Japan', 'JP', NOW(), NOW()),
('Germany', 'DE', NOW(), NOW()),
('India', 'IN', NOW(), NOW()),
('United Kingdom', 'GB', NOW(), NOW()),
('France', 'FR', NOW(), NOW()),
('Italy', 'IT', NOW(), NOW()),
('Brazil', 'BR', NOW(), NOW()),
('Canada', 'CA', NOW(), NOW()),
('South Korea', 'KR', NOW(), NOW()),
('Russia', 'RU', NOW(), NOW()),
('Spain', 'ES', NOW(), NOW()),
('Australia', 'AU', NOW(), NOW()),
('Mexico', 'MX', NOW(), NOW()),
('Indonesia', 'ID', NOW(), NOW()),
('Netherlands', 'NL', NOW(), NOW()),
('Saudi Arabia', 'SA', NOW(), NOW()),
('Turkey', 'TR', NOW(), NOW()),
('Switzerland', 'CH', NOW(), NOW()),
('Poland', 'PL', NOW(), NOW()),
('Belgium', 'BE', NOW(), NOW()),
('Argentina', 'AR', NOW(), NOW()),
('Sweden', 'SE', NOW(), NOW()),
('Norway', 'NO', NOW(), NOW()),
('Austria', 'AT', NOW(), NOW()),
('Thailand', 'TH', NOW(), NOW()),
('United Arab Emirates', 'AE', NOW(), NOW()),
('Israel', 'IL', NOW(), NOW()),
('Singapore', 'SG', NOW(), NOW()),
('Malaysia', 'MY', NOW(), NOW()),
('Denmark', 'DK', NOW(), NOW()),
('South Africa', 'ZA', NOW(), NOW()),
('Finland', 'FI', NOW(), NOW()),
('Ireland', 'IE', NOW(), NOW()),
('Chile', 'CL', NOW(), NOW()),
('Philippines', 'PH', NOW(), NOW()),
('Portugal', 'PT', NOW(), NOW()),
('Greece', 'GR', NOW(), NOW()),
('Czech Republic', 'CZ', NOW(), NOW()),
('Romania', 'RO', NOW(), NOW()),
('New Zealand', 'NZ', NOW(), NOW()),
('Peru', 'PE', NOW(), NOW()),
('Hungary', 'HU', NOW(), NOW()),
('Qatar', 'QA', NOW(), NOW()),
('Kuwait', 'KW', NOW(), NOW()),
('Ukraine', 'UA', NOW(), NOW()),
('Colombia', 'CO', NOW(), NOW()),
('Vietnam', 'VN', NOW(), NOW()),
('Bangladesh', 'BD', NOW(), NOW()),
('Pakistan', 'PK', NOW(), NOW()),
('Egypt', 'EG', NOW(), NOW()),
('Nigeria', 'NG', NOW(), NOW())
ON DUPLICATE KEY UPDATE 
  name = VALUES(name),
  updatedAt = NOW();
