const Country = require("../models/country.model");

// Leggyakoribb 50+ ország listája
const countries = [
  { name: "United States", code: "US" },
  { name: "China", code: "CN" },
  { name: "Japan", code: "JP" },
  { name: "Germany", code: "DE" },
  { name: "India", code: "IN" },
  { name: "United Kingdom", code: "GB" },
  { name: "France", code: "FR" },
  { name: "Italy", code: "IT" },
  { name: "Brazil", code: "BR" },
  { name: "Canada", code: "CA" },
  { name: "South Korea", code: "KR" },
  { name: "Russia", code: "RU" },
  { name: "Spain", code: "ES" },
  { name: "Australia", code: "AU" },
  { name: "Mexico", code: "MX" },
  { name: "Indonesia", code: "ID" },
  { name: "Netherlands", code: "NL" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Turkey", code: "TR" },
  { name: "Switzerland", code: "CH" },
  { name: "Poland", code: "PL" },
  { name: "Belgium", code: "BE" },
  { name: "Argentina", code: "AR" },
  { name: "Sweden", code: "SE" },
  { name: "Norway", code: "NO" },
  { name: "Austria", code: "AT" },
  { name: "Thailand", code: "TH" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "Israel", code: "IL" },
  { name: "Singapore", code: "SG" },
  { name: "Malaysia", code: "MY" },
  { name: "Denmark", code: "DK" },
  { name: "South Africa", code: "ZA" },
  { name: "Finland", code: "FI" },
  { name: "Ireland", code: "IE" },
  { name: "Chile", code: "CL" },
  { name: "Philippines", code: "PH" },
  { name: "Portugal", code: "PT" },
  { name: "Greece", code: "GR" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Romania", code: "RO" },
  { name: "New Zealand", code: "NZ" },
  { name: "Peru", code: "PE" },
  { name: "Hungary", code: "HU" },
  { name: "Qatar", code: "QA" },
  { name: "Kuwait", code: "KW" },
  { name: "Ukraine", code: "UA" },
  { name: "Colombia", code: "CO" },
  { name: "Vietnam", code: "VN" },
  { name: "Bangladesh", code: "BD" },
  { name: "Pakistan", code: "PK" },
  { name: "Egypt", code: "EG" },
  { name: "Nigeria", code: "NG" },
  { name: "Kenya", code: "KE" },
  { name: "Morocco", code: "MA" },
  { name: "Algeria", code: "DZ" },
  { name: "Tunisia", code: "TN" },
  { name: "Ghana", code: "GH" },
  { name: "Ethiopia", code: "ET" },
  { name: "Tanzania", code: "TZ" },
  { name: "Uganda", code: "UG" },
  { name: "Ivory Coast", code: "CI" },
  { name: "Senegal", code: "SN" },
  { name: "Cameroon", code: "CM" },
  { name: "Angola", code: "AO" },
  { name: "Mozambique", code: "MZ" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
  { name: "Mali", code: "ML" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Niger", code: "NE" },
  { name: "Rwanda", code: "RW" },
  { name: "Benin", code: "BJ" },
  { name: "Burundi", code: "BI" },
  { name: "Guinea", code: "GN" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Togo", code: "TG" },
  { name: "Eritrea", code: "ER" },
  { name: "Liberia", code: "LR" },
  { name: "Central African Republic", code: "CF" },
  { name: "Mauritania", code: "MR" },
  { name: "Gambia", code: "GM" },
  { name: "Botswana", code: "BW" },
  { name: "Namibia", code: "NA" },
  { name: "Gabon", code: "GA" },
  { name: "Lesotho", code: "LS" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Mauritius", code: "MU" },
  { name: "Eswatini", code: "SZ" },
  { name: "Djibouti", code: "DJ" },
  { name: "Comoros", code: "KM" },
  { name: "Cape Verde", code: "CV" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Seychelles", code: "SC" },
];

async function seedCountries() {
  try {
    for (const country of countries) {
      await Country.findOrCreate({
        where: { code: country.code },
        defaults: country,
      });
    }
    console.log("Countries seeded successfully");
  } catch (error) {
    console.error("Error seeding countries:", error);
  }
}

module.exports = { seedCountries, countries };
