const logger = require("../logger");

// Sikeres válasz
exports.successResponse = (
  res,
  message,
  data = null,
  isNeedLog = false,
  statusCode = 200,
  extra = null
) => {
  if (isNeedLog) {
    logger.info(
      `${message}
      ${data ? JSON.stringify(data) : null}`
    );
  }

  // Ellenőrizzük, hogy az adat objektum-e, és van-e benne `data` mező
  const isObject =
    typeof data === "object" && !Array.isArray(data) && data !== null;
  const hasDataField = isObject && data.hasOwnProperty("data");

  // Ha van `data` mező és az objektum tartalmaz más attribútumokat is
  if (hasDataField) {
    const { data: nestedData, ...rest } = data; // Bontsd ki a `data` mezőt és a többit
    return res.status(statusCode).json({
      status: "OK",
      message,
      data: nestedData,
      ...rest,
    });
  }

  // Alapértelmezett válasz, ha nincs speciális `data` mező
  return res.status(statusCode).json({
    status: "OK",
    message,
    data,
    ...(extra !== null && { extra }),
  });
};

// Error kódok definíciója
const ERROR_CODES = {
  // Auth hibák
  AUTH: {
    JWT_EXPIRED: "AUTH.JWT_EXPIRED",
    JWT_INVALID: "AUTH.JWT_INVALID", 
    JWT_MISSING: "AUTH.JWT_MISSING",
    INVALID_CREDENTIALS: "AUTH.INVALID_CREDENTIALS",
    EMAIL_NOT_VERIFIED: "AUTH.EMAIL_NOT_VERIFIED",
    USER_INACTIVE: "AUTH.USER_INACTIVE",
    USER_NOT_FOUND: "AUTH.USER_NOT_FOUND",
    INSUFFICIENT_PERMISSIONS: "AUTH.INSUFFICIENT_PERMISSIONS",
    REFRESH_TOKEN_EXPIRED: "AUTH.REFRESH_TOKEN_EXPIRED",
    REFRESH_TOKEN_INVALID: "AUTH.REFRESH_TOKEN_INVALID"
  },
  
  // User hibák
  USER: {
    CREATE_FAILED: "USER.CREATE_FAILED",
    UPDATE_FAILED: "USER.UPDATE_FAILED",
    DELETE_FAILED: "USER.DELETE_FAILED",
    NOT_FOUND: "USER.NOT_FOUND",
    EMAIL_EXISTS: "USER.EMAIL_EXISTS",
    PASSWORD_CHANGE_FAILED: "USER.PASSWORD_CHANGE_FAILED",
    PASSWORD_MISMATCH: "USER.PASSWORD_MISMATCH",
    QUERY_FAILED: "USER.QUERY_FAILED"
  },
  
  // Email verifikáció hibák
  EMAIL_VERIFICATION: {
    TOKEN_EXPIRED: "EMAIL_VERIFICATION.TOKEN_EXPIRED",
    TOKEN_INVALID: "EMAIL_VERIFICATION.TOKEN_INVALID",
    ALREADY_VERIFIED: "EMAIL_VERIFICATION.ALREADY_VERIFIED",
    SEND_FAILED: "EMAIL_VERIFICATION.SEND_FAILED"
  },
  
  // Password reset hibák
  PASSWORD_RESET: {
    REQUEST_FAILED: "PASSWORD_RESET.REQUEST_FAILED",
    TOKEN_EXPIRED: "PASSWORD_RESET.TOKEN_EXPIRED",
    TOKEN_INVALID: "PASSWORD_RESET.TOKEN_INVALID",
    SUBMIT_FAILED: "PASSWORD_RESET.SUBMIT_FAILED",
    EMAIL_SEND_FAILED: "PASSWORD_RESET.EMAIL_SEND_FAILED"
  },
  
  // Contact hibák
  CONTACT: {
    CREATE_FAILED: "CONTACT.CREATE_FAILED",
    UPDATE_FAILED: "CONTACT.UPDATE_FAILED",
    DELETE_FAILED: "CONTACT.DELETE_FAILED",
    NOT_FOUND: "CONTACT.NOT_FOUND",
    QUERY_FAILED: "CONTACT.QUERY_FAILED",
    EMAIL_SEND_FAILED: "CONTACT.EMAIL_SEND_FAILED"
  },
  
  // FAQ hibák
  FAQ: {
    CREATE_FAILED: "FAQ.CREATE_FAILED",
    UPDATE_FAILED: "FAQ.UPDATE_FAILED",
    DELETE_FAILED: "FAQ.DELETE_FAILED",
    NOT_FOUND: "FAQ.NOT_FOUND",
    QUERY_FAILED: "FAQ.QUERY_FAILED"
  },
  
  // FAQ Category hibák
  FAQ_CATEGORY: {
    CREATE_FAILED: "FAQ_CATEGORY.CREATE_FAILED",
    UPDATE_FAILED: "FAQ_CATEGORY.UPDATE_FAILED",
    DELETE_FAILED: "FAQ_CATEGORY.DELETE_FAILED",
    NOT_FOUND: "FAQ_CATEGORY.NOT_FOUND",
    QUERY_FAILED: "FAQ_CATEGORY.QUERY_FAILED"
  },
  
  // File hibák
  FILE: {
    UPLOAD_FAILED: "FILE.UPLOAD_FAILED",
    DELETE_FAILED: "FILE.DELETE_FAILED",
    NOT_FOUND: "FILE.NOT_FOUND",
    QUERY_FAILED: "FILE.QUERY_FAILED",
    INVALID_FILE: "FILE.INVALID_FILE",
    FILE_TOO_LARGE: "FILE.FILE_TOO_LARGE",
    INVALID_FILE_TYPE: "FILE.INVALID_FILE_TYPE"
  },
  
  // Subscriber hibák
  SUBSCRIBER: {
    CREATE_FAILED: "SUBSCRIBER.CREATE_FAILED",
    UPDATE_FAILED: "SUBSCRIBER.UPDATE_FAILED",
    DELETE_FAILED: "SUBSCRIBER.DELETE_FAILED",
    NOT_FOUND: "SUBSCRIBER.NOT_FOUND",
    QUERY_FAILED: "SUBSCRIBER.QUERY_FAILED",
    EMAIL_EXISTS: "SUBSCRIBER.EMAIL_EXISTS"
  },
  
  // Testimonial hibák
  TESTIMONIAL: {
    CREATE_FAILED: "TESTIMONIAL.CREATE_FAILED",
    UPDATE_FAILED: "TESTIMONIAL.UPDATE_FAILED",
    DELETE_FAILED: "TESTIMONIAL.DELETE_FAILED",
    NOT_FOUND: "TESTIMONIAL.NOT_FOUND",
    QUERY_FAILED: "TESTIMONIAL.QUERY_FAILED"
  },
  
  // Hero Slider hibák
  HERO_SLIDER: {
    CREATE_FAILED: "HERO_SLIDER.CREATE_FAILED",
    UPDATE_FAILED: "HERO_SLIDER.UPDATE_FAILED",
    DELETE_FAILED: "HERO_SLIDER.DELETE_FAILED",
    NOT_FOUND: "HERO_SLIDER.NOT_FOUND",
    QUERY_FAILED: "HERO_SLIDER.QUERY_FAILED"
  },
  
  // Product Category Group hibák
  PRODUCT_CATEGORY_GROUP: {
    CREATE_FAILED: "PRODUCT_CATEGORY_GROUP.CREATE_FAILED",
    UPDATE_FAILED: "PRODUCT_CATEGORY_GROUP.UPDATE_FAILED",
    DELETE_FAILED: "PRODUCT_CATEGORY_GROUP.DELETE_FAILED",
    NOT_FOUND: "PRODUCT_CATEGORY_GROUP.NOT_FOUND",
    QUERY_FAILED: "PRODUCT_CATEGORY_GROUP.QUERY_FAILED"
  },
  
  // Product Category hibák
  PRODUCT_CATEGORY: {
    CREATE_FAILED: "PRODUCT_CATEGORY.CREATE_FAILED",
    UPDATE_FAILED: "PRODUCT_CATEGORY.UPDATE_FAILED",
    DELETE_FAILED: "PRODUCT_CATEGORY.DELETE_FAILED",
    NOT_FOUND: "PRODUCT_CATEGORY.NOT_FOUND",
    QUERY_FAILED: "PRODUCT_CATEGORY.QUERY_FAILED"
  },
  
  // Product Subcategory hibák
  PRODUCT_SUBCATEGORY: {
    CREATE_FAILED: "PRODUCT_SUBCATEGORY.CREATE_FAILED",
    UPDATE_FAILED: "PRODUCT_SUBCATEGORY.UPDATE_FAILED",
    DELETE_FAILED: "PRODUCT_SUBCATEGORY.DELETE_FAILED",
    NOT_FOUND: "PRODUCT_SUBCATEGORY.NOT_FOUND",
    QUERY_FAILED: "PRODUCT_SUBCATEGORY.QUERY_FAILED"
  },
  
  // Product hibák
  PRODUCT: {
    CREATE_FAILED: "PRODUCT.CREATE_FAILED",
    UPDATE_FAILED: "PRODUCT.UPDATE_FAILED",
    DELETE_FAILED: "PRODUCT.DELETE_FAILED",
    NOT_FOUND: "PRODUCT.NOT_FOUND",
    QUERY_FAILED: "PRODUCT.QUERY_FAILED"
  },
  
  // Reference hibák
  REFERENCE: {
    CREATE_FAILED: "REFERENCE.CREATE_FAILED",
    UPDATE_FAILED: "REFERENCE.UPDATE_FAILED",
    DELETE_FAILED: "REFERENCE.DELETE_FAILED",
    NOT_FOUND: "REFERENCE.NOT_FOUND",
    QUERY_FAILED: "REFERENCE.QUERY_FAILED"
  },
  
  // Media hibák
  MEDIA: {
    CREATE_FAILED: "MEDIA.CREATE_FAILED",
    UPDATE_FAILED: "MEDIA.UPDATE_FAILED",
    DELETE_FAILED: "MEDIA.DELETE_FAILED",
    NOT_FOUND: "MEDIA.NOT_FOUND",
    QUERY_FAILED: "MEDIA.QUERY_FAILED"
  },
  
  // Partner hibák
  PARTNER: {
    CREATE_FAILED: "PARTNER.CREATE_FAILED",
    UPDATE_FAILED: "PARTNER.UPDATE_FAILED",
    DELETE_FAILED: "PARTNER.DELETE_FAILED",
    NOT_FOUND: "PARTNER.NOT_FOUND",
    QUERY_FAILED: "PARTNER.QUERY_FAILED"
  },
  
  // DownloadableItem hibák
  DOWNLOADABLE_ITEM: {
    CREATE_FAILED: "DOWNLOADABLE_ITEM.CREATE_FAILED",
    UPDATE_FAILED: "DOWNLOADABLE_ITEM.UPDATE_FAILED",
    DELETE_FAILED: "DOWNLOADABLE_ITEM.DELETE_FAILED",
    NOT_FOUND: "DOWNLOADABLE_ITEM.NOT_FOUND",
    QUERY_FAILED: "DOWNLOADABLE_ITEM.QUERY_FAILED"
  },
  
  // DownloadableCategory hibák
  DOWNLOADABLE_CATEGORY: {
    CREATE_FAILED: "DOWNLOADABLE_CATEGORY.CREATE_FAILED",
    UPDATE_FAILED: "DOWNLOADABLE_CATEGORY.UPDATE_FAILED",
    DELETE_FAILED: "DOWNLOADABLE_CATEGORY.DELETE_FAILED",
    NOT_FOUND: "DOWNLOADABLE_CATEGORY.NOT_FOUND",
    QUERY_FAILED: "DOWNLOADABLE_CATEGORY.QUERY_FAILED"
  },
  
  // InternationalContact hibák
  INTERNATIONAL_CONTACT: {
    CREATE_FAILED: "INTERNATIONAL_CONTACT.CREATE_FAILED",
    UPDATE_FAILED: "INTERNATIONAL_CONTACT.UPDATE_FAILED",
    DELETE_FAILED: "INTERNATIONAL_CONTACT.DELETE_FAILED",
    NOT_FOUND: "INTERNATIONAL_CONTACT.NOT_FOUND",
    QUERY_FAILED: "INTERNATIONAL_CONTACT.QUERY_FAILED"
  },
  
  // Glossary hibák
  GLOSSARY: {
    CREATE_FAILED: "GLOSSARY.CREATE_FAILED",
    UPDATE_FAILED: "GLOSSARY.UPDATE_FAILED",
    DELETE_FAILED: "GLOSSARY.DELETE_FAILED",
    NOT_FOUND: "GLOSSARY.NOT_FOUND",
    QUERY_FAILED: "GLOSSARY.QUERY_FAILED"
  },

  // Legal doc hibák
  LEGAL_DOC: {
    CREATE_FAILED: "LEGAL_DOC.CREATE_FAILED",
    UPDATE_FAILED: "LEGAL_DOC.UPDATE_FAILED",
    DELETE_FAILED: "LEGAL_DOC.DELETE_FAILED",
    NOT_FOUND: "LEGAL_DOC.NOT_FOUND",
    QUERY_FAILED: "LEGAL_DOC.QUERY_FAILED"
  },

  // Social media page hibák
  SOCIAL_MEDIA_PAGE: {
    CREATE_FAILED: "SOCIAL_MEDIA_PAGE.CREATE_FAILED",
    UPDATE_FAILED: "SOCIAL_MEDIA_PAGE.UPDATE_FAILED",
    DELETE_FAILED: "SOCIAL_MEDIA_PAGE.DELETE_FAILED",
    NOT_FOUND: "SOCIAL_MEDIA_PAGE.NOT_FOUND",
    QUERY_FAILED: "SOCIAL_MEDIA_PAGE.QUERY_FAILED"
  },
  
  // Általános hibák
  GENERAL: {
    INTERNAL_ERROR: "GENERAL.INTERNAL_ERROR",
    VALIDATION_ERROR: "GENERAL.VALIDATION_ERROR",
    NOT_FOUND: "GENERAL.NOT_FOUND",
    UNAUTHORIZED: "GENERAL.UNAUTHORIZED",
    FORBIDDEN: "GENERAL.FORBIDDEN",
    BAD_REQUEST: "GENERAL.BAD_REQUEST"
  }
};

// Hibás válasz
exports.errorResponse = (
  res,
  message,
  errorCode,
  isNeedLog = true,
  statusCode = 400,
  errorDetails = null
) => {
  if (isNeedLog) {
    logger.error(
      `${message} | Code: ${errorCode}
      ${errorDetails ? JSON.stringify(errorDetails) : null}`
    );
  }
  
  return res.status(statusCode).json({
    status: "FAILED",
    message,
    errorCode,
    ...(errorDetails && { details: errorDetails })
  });
};

// Strukturált error kezelése (deprecated - használd az error-helper.js-ből)
exports.handleError = (res, error, defaultMessage, defaultCode) => {
  if (error && error.isStructured) {
    return exports.errorResponse(res, error.message, error.code);
  } else {
    return exports.errorResponse(res, defaultMessage, defaultCode);
  }
};

// Error kódok exportálása
exports.ERROR_CODES = ERROR_CODES;
